### PR TITLE
add auto-ui

### PR DESCRIPTION
**Pull request by zhaopuming**
[auto-ui](https://github.com/auto-stack/auto-ui) is a UI framework based on GPUI and [GPUI-Component](https://github.com/longbridge/gpui-component).

auto-ui uses [auto-lang](https://github.com/auto-stack/auto-lang), a scripting language written in Rust,
to describe the UI layout, similar to `rsx!` macros in [Dioxus](https://github.com/DioxusLabs/dioxus).

Here is a simple Counter example written in auto-ui:

```rust
widget counter {
    model {
        var count = 0
    }
    view {
        button("+") {
            onclick: || count = count + 1
        }
        text(f"Count: $count")
        button("-") {
            onclick: || count = count - 1
        }
        button("reset") {
            onclick: || count = 0
        }
    }
}
```

and the UI it generates:

auto-ui counter example

### CODE REVIEW

**Comment by zhaopuming** [comment]
Sorry, the repo is mirror to our project hosted in gitee.com, and was an internal project that open up recently. So the commit history is not entirely github users.

**Comment by notpeter** [comment]
Cla bot is complaining about your commit to this repo not your linked repo.

Basically you need to (1) associate the email used in [your commit](https://github.com/zed-industries/awesome/commit/663e509626a804b3db1b67ea227a8757c1cd0026.patch) with your GitHub account, (2) Sign the [Zed CLA](https://zed.dev/cla) (scroll to the bottom) (3) mention cla-bot in a comment so it can recheck.

**Comment by zhaopuming** [comment]
Thanks for the note :-)

@cla-bot please check again.

**Comment by notpeter** [comment]
@cla-bot check

**Comment by notpeter** [comment]
Looks like you still need to add/verify your email here: https://github.com/settings/emails

**Comment by zhaopuming** [comment]
Seems like I have to switch to a new pull request with a commit that is commited with my Github account/email

**Pull request closed without merging**
